### ISSUE TITLE
…

### ISSUE THREAD

**Issue by tyan-boot** [tgh980122/bbq#2]
这是什么。

**Comment by equationl** [comment]
我也想问

**Comment by tyan-boot** [comment]
神经

--- 原始邮件 ---

发件人： "equationl" notifications@github.com
已发： 2015年1月18日 下午7:00
收件人： "tgh980122/bbq" bbq@noreply.github.com
抄送： "tgh980122" tyan-boot@outlook.com
主题： Re: [bbq] … (#2)

我也想问

---
