### ISSUE TITLE
求加友链

### ISSUE THREAD

**Issue by equationl** [tgh980122/bbq#4]
RTRTRTRTRTRT

**Comment by tyan-boot** [comment]
加你个头…为什么要到GitHub上面给我发邮件。不能直接发啊？

--- 原始邮件 ---

发件人： "equationl" notifications@github.com
已发： 2015年1月19日 下午12:06
收件人： "tgh980122/bbq" bbq@noreply.github.com
主题： [bbq] 求加友链 (#4)

RTRTRTRTRTRT

---

Reply to this email directly or view it on GitHub:
https://github.com/tgh980122/bbq/issues/4

**Comment by tyan-boot** [comment]
等新的CI框架版本写完吧

--- 原始邮件 ---

发件人： "equationl" notifications@github.com
已发： 2015年1月19日 下午12:06
收件人： "tgh980122/bbq" bbq@noreply.github.com
主题： [bbq] 求加友链 (#4)

RTRTRTRTRTRT

---

Reply to this email directly or view it on GitHub:
https://github.com/tgh980122/bbq/issues/4

**Comment by tgh980122** [comment]
回复测试一下

--- Tyan Boot 敬上！ ---

--- 原始邮件 ---

发件人： "equationl" <notifications@github.com>
已发： 2015年1月19日 下午12:06
收件人： "tgh980122/bbq" <bbq@noreply.github.com>
主题： [bbq] 求加友链 (#4)

RTRTRTRTRTRT

---
Reply to this email directly or view it on GitHub:
https://github.com/tgh980122/bbq/issues/4

**Comment by tgh980122** [comment]
我醉了


真是醉了

--- 原始邮件 ---

发件人： "equationl" <notifications@github.com>
已发： 2015年1月19日 下午12:06
收件人： "tgh980122/bbq" <bbq@noreply.github.com>
主题： [bbq] 求加友链 (#4)

RTRTRTRTRTRT

---
Reply to this email directly or view it on GitHub:
https://github.com/tgh980122/bbq/issues/4

**Comment by tgh980122** [comment]
支持不支持makedown
> 试一下

**Comment by tgh980122** [comment]
诶。挺屌
__那么这个呢__

**Comment by tgh980122** [comment]
.......

--- Tyan Boot 敬上！ ---
